export const SOUTH_AFRICAN_LANGUAGES = [
  { code: "en", name: "English" },
  { code: "zu", name: "isiZulu" },
  { code: "af", name: "Afrikaans" },
  { code: "xh", name: "isiXhosa" },
  { code: "st", name: "Sesotho" },
  { code: "tn", name: "Setswana" },
  { code: "ss", name: "siSwati" },
  { code: "ve", name: "Tshivenda" },
  { code: "ts", name: "Xitsonga" },
  { code: "nr", name: "isiNdebele" },
  { code: "nso", name: "Sepedi" },
];

export const GRADE_LEVELS = [
  { value: "foundation", label: "Foundation Phase (Grade 1-3)" },
  { value: "intermediate", label: "Intermediate Phase (Grade 4-6)" },
  { value: "senior", label: "Senior Phase (Grade 7-9)" },
  { value: "fet", label: "FET Phase (Grade 10-12)" },
  { value: "abet", label: "ABET" },
];

export const SUBJECTS = [
  "Mathematics",
  "English",
  "Afrikaans",
  "isiZulu",
  "Life Orientation",
  "Natural Sciences",
  "Social Sciences",
  "Technology",
  "Economic and Management Sciences",
  "Arts and Culture",
  "Physical Education",
  "Life Skills",
];

export const DASHBOARD_SECTIONS = [
  {
    id: "practice-zone",
    title: "Practice Zone",
    description: "Master concepts with interactive quizzes and exercises",
    icon: "brain",
    color: "from-blue-500 to-blue-600",
    tags: ["MCQs", "Essays"],
    href: "/practice-zone",
  },
  {
    id: "games-zone",
    title: "Games Zone",
    description: "Learn through fun educational games and challenges",
    icon: "gamepad-2",
    color: "from-purple-500 to-purple-600",
    tags: ["Math Quiz", "Word Search"],
    href: "/games-zone",
  },
  {
    id: "study-groups",
    title: "Study Groups",
    description: "Collaborate with peers in real-time chat groups",
    icon: "users",
    color: "from-green-500 to-green-600",
    tags: ["Chat", "Video Calls"],
    href: "/study-groups",
  },
  {
    id: "classroom",
    title: "Classroom",
    description: "Access virtual classrooms and live lessons",
    icon: "school",
    color: "from-orange-500 to-orange-600",
    tags: ["Live Stream", "Assignments"],
    href: "/classroom",
  },
  {
    id: "ai-assistants",
    title: "AI Assistants",
    description: "Get personalized help from safe AI tutors",
    icon: "bot",
    color: "from-indigo-500 to-indigo-600",
    tags: ["Safe Chat", "Homework Help"],
    href: "/ai-assistants",
  },
  {
    id: "support-center",
    title: "Support Center",
    description: "Get help, report issues, and access wellness resources",
    icon: "headphones",
    color: "from-rose-500 to-rose-600",
    tags: ["Help Desk", "Wellness"],
    href: "/support-center",
  },
  {
    id: "educational-videos",
    title: "Educational Videos",
    description: "Watch curated educational content by grade level",
    icon: "play-circle",
    color: "from-teal-500 to-teal-600",
    tags: ["Grade 1-12", "ABET"],
    href: "/educational-videos",
  },
  {
    id: "contact",
    title: "Contact",
    description: "Connect with us for support and partnerships",
    icon: "mail",
    color: "from-emerald-500 to-emerald-600",
    tags: ["Live Chat", "Meetings"],
    href: "/contact",
  },
];

export const EDUCATIONAL_GAMES = [
  {
    id: "math-quiz",
    title: "Math Quiz Challenge",
    description: "Test your math skills with timed quizzes across all grade levels.",
    icon: "calculator",
    color: "from-blue-500 to-blue-600",
    grades: "Grades 1-12",
  },
  {
    id: "word-search",
    title: "Word Search",
    description: "Find hidden words in multiple South African languages.",
    icon: "search",
    color: "from-green-500 to-green-600",
    grades: "All Languages",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description: "Improve memory skills by matching educational content pairs.",
    icon: "brain",
    color: "from-purple-500 to-purple-600",
    grades: "All Ages",
  },
  {
    id: "typing-sprint",
    title: "Typing Sprint",
    description: "Improve typing speed and accuracy with educational texts.",
    icon: "keyboard",
    color: "from-orange-500 to-orange-600",
    grades: "Grade 4+",
  },
  {
    id: "science-quiz",
    title: "Science Quiz",
    description: "Explore scientific concepts through interactive quizzes.",
    icon: "flask-conical",
    color: "from-teal-500 to-teal-600",
    grades: "Grade 7-12",
  },
  {
    id: "spelling-bee",
    title: "Spelling Bee",
    description: "Master spelling in English and indigenous languages.",
    icon: "spell-check",
    color: "from-yellow-500 to-yellow-600",
    grades: "Grade 1-8",
  },
  {
    id: "history-quiz",
    title: "SA History Quiz",
    description: "Learn about South African history and heritage.",
    icon: "landmark",
    color: "from-indigo-500 to-indigo-600",
    grades: "Grade 4-12",
  },
  {
    id: "flags-africa",
    title: "African Flags",
    description: "Identify flags and learn about African countries.",
    icon: "flag",
    color: "from-green-500 to-green-600",
    grades: "Geography",
  },
];

export const SAMPLE_VIDEOS = [
  {
    id: "afrikaans-basics",
    title: "Afrikaans Basics",
    description: "Learn basic Afrikaans words and phrases with interactive exercises.",
    duration: "15 minutes",
    grade: "Grade 1-3",
    subject: "Afrikaans",
    thumbnailUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ", // Sample YouTube ID
  },
  {
    id: "grade-1-addition",
    title: "Grade 1 Addition Fun",
    description: "Colorful introduction to addition with counting and visual aids.",
    duration: "12 minutes",
    grade: "Grade 1",
    subject: "Mathematics",
    thumbnailUrl: "https://images.unsplash.com/photo-1632571401005-458e9d244591?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "mental-math-tricks",
    title: "Mental Math Tricks",
    description: "Learn quick calculation techniques for faster problem solving.",
    duration: "20 minutes",
    grade: "Grade 4-6",
    subject: "Mathematics",
    thumbnailUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "photosynthesis-quiz",
    title: "Photosynthesis Interactive Quiz",
    description: "Understand how plants make food through interactive experiments.",
    duration: "18 minutes",
    grade: "Grade 7-9",
    subject: "Natural Sciences",
    thumbnailUrl: "https://images.unsplash.com/photo-1628258334105-2a0b3d6efee1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "telling-time",
    title: "Learning to Tell Time",
    description: "Master reading analog and digital clocks with fun activities.",
    duration: "16 minutes",
    grade: "Grade 2-3",
    subject: "Mathematics",
    thumbnailUrl: "https://images.unsplash.com/photo-1544717301-9cdcb1f5940f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "grade-12-exam-prep",
    title: "Grade 12 Exam Prep",
    description: "Comprehensive revision with memo discussions and exam strategies.",
    duration: "45 minutes",
    grade: "Grade 12",
    subject: "All Subjects",
    thumbnailUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=450",
    youtubeId: "dQw4w9WgXcQ",
  },
];
